# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# Baseurl = name of github repository linked to libertarianinstitute account
#
#
projname: Template
projgoal: >
        Cílem projektu je template stránek AngularJS History AngularJS version 1.0 was released in 2012. Miško Hevery, a Google employee, started to work with AngularJS in 2009. The idea turned out very well, and the project is now officially supported by Google. AngularJS Examples W3Schools' AngularJS tutorial contains lots of AngularJS examples! AngularJS Example
muzetesetesitna: >
        <ul>
        <li>nečekaná odhalení, která vás zaručeně zvednou ze židle;</li>
        <li>užitečné informace, které nikde jinde nenajdete;</li>
        <li>vtipné grafiky, které vás přimějí se zamyslet</li>
        </ul>
title: Libertariani.cz - template
email: michal.kurz@libertariani.cz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/template" # the subpath of your site, e.g. /blog
url: "http://libertarianinstitute.github.io" # the base hostname & protocol for your site
github_username:  libertarianinstitute

# Build settings
markdown: kramdown
